from eve.gateways._get_corp_assets import GetCorpAssetsGateway
from eve.gateways._get_inventory_locations import GetInventoryLocationGateway
from eve.gateways._get_market_prices import GetMarketPricesGateway
from eve.gateways._get_type_info import GetTypeInfoGateway
from eve.gateways._get_markets_groups import GetMarketGroupsGateway
from eve.gateways._get_corp_assets_names import GetCorpAssetsNamesGateway
from eve.gateways._get_foreign_structures import GetForeignStructuresGateway
from eve.gateways._get_inventory_location_names import GetInventoryLocationNamesGateway
